HerculesSystem/Controllers/ZoneSitesController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using HerculesSystem.Models;
namespace HerculesSystem.Controllers
{
    public class ZoneSitesController : Controller
    {
        // GET: ZoneSites
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            return GetView(request);
        }
        private JsonResult GetView(DataSourceRequest request)
        {
            return Json(GetData().ToDataSourceResult(request));
        }
        private IEnumerable<dynamic> GetData()
        {
            
            var ZoneLogger = new hercules_dbEntities();

            var result = from a in ZoneLogger.zones2
                         select new
                         {
                             ID = a.ID,
                             ZoneName = a.ZoneName,
                             Status = a.Status,
                             CreationDate = a.CreationDate
                         };
            

            return result;
        }


        public ActionResult Create()
        {
            return View();
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, zone product)
        {
          //  DataClasses1DataContext dt = new DataClasses1DataContext();
            if (product != null)
              //  && ModelState.IsValid
            {

                using (var db = new hercules_dbEntities())
                {
                    var result = from u in db.zones2 where (u.ID == product.ID) select u;
                    if (result.Count() != 0)
                    {
                        var dbuser = result.First();
                        dbuser.ZoneName = product.ZoneName;
                        dbuser.Status = product.Status.Value;
                        

                        db.SaveChanges();
                    }
                } 
              

            }

            return Json(new[] { product }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult CreateLogger(zone zo)
        {
            if (ModelState.IsValid)
            {
                using (var northwind = new hercules_dbEntities())
                {
                    // Create a new Product entity and set its properties from the posted ProductViewModel
                    var entity = new zone
                    {

                        ZoneName = zo.ZoneName,
                        Status = true,
                        CreationDate = DateTime.Now

                    };
                    // Add the entity
                    northwind.zones2.Add(entity);
                    // Insert the entity in the database
                    northwind.SaveChanges();
                    // Get the ProductID generated by the database

                }
            
            }
            return Redirect("List");
        }



    }
}

HerculesSystem/Views/ZoneSites/Create.cshtml
@model HerculesSystem.Models.zone
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
}

HerculesSystem/Views/ZoneSites/List.cshtml
@model HerculesSystem.Models.zone

    @{
        ViewBag.Title = "Zone List";
    }

    <h2>Create</h2>

    @using (Html.BeginForm("CreateLogger", "ZoneSites"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        
     <p>
         @Html.TextBoxFor(model => model.ZoneName, new { @class = "form-control", placeholder = "Zone Name", style = "width:170px" })
         @Html.ValidationMessageFor(model => model.ZoneName)
     </p>
    <p>
        <input type="submit" value="Create" class="btn btn-default" width="170" id="btnCreate" />

    </p>
        @section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
        }
    }

    <div id="grid" class="grid">
        <h2>List</h2>
        @(Html.Kendo().Grid<HerculesSystem.Models.zone>().Name("GridLoggers")
              .DataSource(d => d.Ajax()
                
                .Model(c =>
                {
                    c.Id("ID");
                    c.Field("ZoneName", typeof(string));
                    c.Field("Status", typeof(bool));
                    c.Field("CreationDate", typeof(DateTime)).Editable(false);
                    c.Field("AmountSite", typeof(int)).Editable(false);

                })
                .Read(r => r.Action("Read", "ZoneSites"))
                .Update(update => update.Action("Edit", "ZoneSites"))

               )
                .Columns(columns =>
                {
                    columns.Bound("ZoneName").Title("Zone Name");
                    columns.Bound("CreationDate").Title("Creation Date").Format("{0:dd/MM/yyyy HH:mm:ss}").EditorTemplateName("CreationDate");
                    columns.Bound("AmountSite").Title("Amount Site");
                    columns.Bound("Status").Title("Status");
                    columns.Command(command => { command.Edit(); }).Title("Detail");

                })
                       
                        .Editable(editable => editable.Mode(GridEditMode.InLine))
                        .Sortable()
                        .Filterable()
                        .Pageable()

        )

        <script type="text/javascript">
            var detailsTemplate = kendo.template($("#template").html());

            function showDetails(e) {
                e.preventDefault();
                window.location.href = "Detail";
            }

            function checkMark(mark) {
                if (mark == 0 || mark == null)
                    return 'absert';
                else
                    return Activo;
            }

            function error_handler(e) {
                if (e.errors) {
                    var message = "Errors:\n";
                    $.each(e.errors, function (key, value) {
                        if ('errors' in value) {
                            $.each(value.errors, function () {
                                message += this + "\n";
                            });
                        }
                    });
                    alert(message);
                }
            }
        </script>


    </div>