HerculesSystem/Models/logger.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;


using System.Web;

namespace HerculesSystem.Models
{
    [Table("loggers")]
    public partial class logger
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID { get; set; }

        [StringLength(50)]
        public string LoggerType { get; set; }

      
        public string LoggerSerialNumber { get; set; }

        [Required(ErrorMessage = "Campo obligatorio.")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Solo números")]
        public string LoggerSMSNumber { get; set; }
         
        
        public DateTime LastCallIn { get; set; }
        
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int SignalLevel { get; set; }
        public double BatteryLevel { get; set; }

        public string LoggerGSMNumber { get; set; }

        public int LoggerRateMs { get; set; }
       
        public string Notes { get; set; }

        public string owner_name { get; set; }

        public int SitedID { get; set; }

        public int OwnerAccount { get; set; }

        public bool WithSite { get; set; }




       

       

       

      

       

        
    }
}

HerculesSystem/Models/loggers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class loggers
    {
        public int ID { get; set; }
       
        public string LoggerType { get; set; }
        public string LoggerSoftware { get; set; }
        public string LoggerSerialNumber { get; set; }
        [Required]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Count must be a natural number")]
        [Remote("LoggerValidation", "Validations", ErrorMessage = "Logger Already Exists", AdditionalFields = "InitialSMS")]  

        public string LoggerSMSNumber { get; set; }
        public string LoggerGSMNumber { get; set; }
        public Nullable<int> OwnerAccount { get; set; }
        public Nullable<System.DateTime> LastCallIn { get; set; }
        public Nullable<System.DateTime> RST { get; set; }
        public Nullable<int> SignalLevel { get; set; }
        public Nullable<double> BatteryLevel { get; set; }
        public Nullable<int> LogRateMs { get; set; }
        public Nullable<int> NetID { get; set; }
        public Nullable<int> LAC { get; set; }
        public Nullable<int> CellID { get; set; }
        public Nullable<double> MastLongitude { get; set; }
        public Nullable<double> MastLatitude { get; set; }
        public Nullable<long> DataCount { get; set; }
        public string Notes { get; set; }
        public string LastMessageType { get; set; }
        public Nullable<int> CallFrequency { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> LoggerStatus { get; set; }
        public string Adress { get; set; }
        public string LatEast { get; set; }
        public string LongNorth { get; set; }
        public string HeightAOD { get; set; }
        public Nullable<int> SiteID { get; set; }
        [Required]
        public string LoggerTypeClass { get; set; }
    
        public virtual company company { get; set; }
    }
}

HerculesSystem/Controllers/LoggerController.cs
using HerculesSystem.Models;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;

namespace HerculesSystem.Controllers
{
    public class LoggerController : Controller
    {
        // GET: Logger

        
       
        public ActionResult ListLogger()
        {
            return View();
        }


        public ActionResult Loading()
        {
            return View();
        }



        public ActionResult Index(string ID)
        {
            ViewData["id"] = ID;
            Session["id"] = ViewData["id"];
            
            return View();
        }

        public ActionResult DetailButton(string ID)
        {
            ViewData["id"] = ID;
            
            
            return RedirectToAction("Index", new { id = ID });
        }

        public ActionResult FilterButton([DataSourceRequest] DataSourceRequest request, int? zone, int?logger)
        {

            //return RedirectToAction("ListLogger", new { zone = zone,logger = logger });
            return GetView(request);
        }



        private IEnumerable<dynamic> GetData()
        {
        var db = new hercules_dbEntities();
        var zone = new ZoneLogger();
        var result = from a in db.loggers
                        //join b in db.sites
                        //    on a.ID equals b.LoggerID into abc from ab in abc.DefaultIfEmpty()
                        join c in db.users
                            on a.OwnerAccount equals c.Id
                        select new
                        {
                            ID = a.ID,
                            LoggerSMSNumber = a.LoggerSMSNumber,
                            BatteryLevel = a.BatteryLevel,
                            LastCallIn = a.LastCallIn,
                            LoggerSerialNumber = a.LoggerSerialNumber,
                            LoggerType = a.LoggerType,
                            SignalLevel = a.SignalLevel,                        
                            Owner = c.FirstName +" "+ c.LastName,
                            OwnerID = c.Id,
                            a.LoggerStatus,
                            a.CreationDate,
                            a.Adress
                            
                        };
        result = result.Where(u => u.LoggerStatus == true);
        result = result.OrderBy(u => u.CreationDate);
        return result ;
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            return GetView(request);
        }

        private JsonResult GetView(DataSourceRequest request)
        {
            return Json(GetData().ToDataSourceResult(request));
        }

        [HttpPost]
        public ActionResult RefreshSelfUpdatingPartial()
        {

            // Setting the Models Content
            // ...

            return PartialView("_SelfUpdatingPartial");
        }

        public ActionResult Create()
        {
            //var log =  logger();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(loggers d)
        {
            if (ModelState.IsValid)
            {
                using (var northwind = new hercules_dbEntities())
                {
                    //Get max ID table loggers
                    var crum = northwind.loggers.Max(sd => sd.ID);

                    int current_id = Convert.ToInt32(crum.ToString());

                    // Create a new Product entity and set its properties from the posted ProductViewModel
                    var entity = new loggers
                    {

                        ID = current_id + 1,
                        LoggerSMSNumber = d.LoggerSMSNumber,
                        LoggerSerialNumber = d.LoggerSerialNumber,
                        Notes = d.Notes,
                        CreationDate = DateTime.Now,
                        Adress = d.Adress,
                        LatEast = d.LatEast,
                        LongNorth = d.LongNorth,
                        HeightAOD = d.HeightAOD,
                        LoggerTypeClass = d.LoggerTypeClass,
                        SiteID = d.SiteID,
                        OwnerAccount = Convert.ToInt16(Session["LogedUserID"].ToString()),
                        CompanyID = Convert.ToInt16(Session["CompanyID"].ToString()),
                        LoggerStatus = true

                    };
                    // Add the entity
                    northwind.loggers.Add(entity);
                    // Insert the entity in the database
                    northwind.SaveChanges();
                    // Get the ProductID generated by the database

                }

                return RedirectToAction("ListLogger");
                // return View();

            }
            else
            {
                return View();
            }
        }

        public ActionResult Delete([DataSourceRequest] DataSourceRequest request,loggers log)
        {
            using (var db = new hercules_dbEntities())
            {
                   var result = from u in db.loggers where (u.ID == log.ID) select u;
                    if (result.Count() != 0)
                    {
                        var dbuser = result.First();
                        dbuser.LoggerStatus = false;
     
                        db.SaveChanges();
                    }
            }

            return Json(new[] { log }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Edit(int ID)
        {
            hercules_dbEntities db = new hercules_dbEntities();

            return View("Edit", db.loggers.Find(ID));
        }

        [HttpPost]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, loggers us)
        {

            if (ModelState.IsValid)
            {
                using (var db = new hercules_dbEntities())
                {
                    var result = from u in db.loggers where (u.ID == us.ID) select u;
                    if (result.Count() != 0)
                    {
                        var dblogger = result.First();

                        dblogger.LoggerSMSNumber = us.LoggerSMSNumber;
                        dblogger.LoggerSerialNumber = us.LoggerSerialNumber;
                        dblogger.Notes = us.Notes;
                        dblogger.Adress = us.Adress;
                        dblogger.LatEast = us.LatEast;
                        dblogger.LongNorth = us.LongNorth;
                        dblogger.HeightAOD = us.HeightAOD;
                        dblogger.LoggerTypeClass = us.LoggerTypeClass;
                        dblogger.SiteID = us.SiteID;
                      

                        db.SaveChanges();
                    }
                }
            }


            return RedirectToAction("ListLogger");
        }
    }
  
}

HerculesSystem/Views/Logger/Create.cshtml
@model HerculesSystem.Models.logger

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("CreateLogger","Logger"))
{ 
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
     
    <div>
        <p>
            @Html.TextBoxFor(model => model.LoggerSMSNumber, new { @class = "form-control", placeholder = "SMS", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.LoggerSMSNumber)
        </p>

        <p>
            @Html.TextBoxFor(model => model.LoggerSerialNumber, new { @class = "form-control", placeholder = "Serial Number", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.LoggerSerialNumber)
        </p>
        <p>
            
            @(Html.Kendo().DropDownListFor(model => model.OwnerAccount)
                .DataTextField("UserName") //Specifies which property of the Product to be used by the dropdownlist as a text.
                .DataValueField("ID") //Specifies which property of the Product to be used by the dropdownlist as a value.
                .HtmlAttributes(new { style = "width:170px" })
                .OptionLabel("Owner")
                .DataSource(source =>
                {
                    source.Read(read =>
                    {
                        read.Action("GetUser", "Helper"); //Set the Action and Controller name
                    }); //If true the DataSource will not filter the data on the client.
                })
            )

        </p>
       
        <p>
            @(Html.CheckBoxFor(model => model.WithSite)

            )
            @(Html.Label("Con Sites"))
        </p>
        <div id="ValidateMyContents">
            <p>
              @(Html.Kendo().DropDownListFor(m => m.SitedID)
              .Name("SitedID")
              .Enable(false)
              .DataTextField("Adress")
              .DataValueField("ID")
              .DataSource(source =>
                  {
                      source.Read(read =>
                      {
                          read.Action("GetSites", "Helper"); //Set the Action and Controller name
                      }); //If true the DataSource will not filter the data on the client.
                  })

                )
                <script>
                    $('.SitedID').kendoDropDownList();
                </script>


            </p>
            <span id="status"></span>
        </div>
        <p>
            @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", placeholder = "Notes", style = "width:175px" })
            @Html.ValidationMessageFor(model => model.Notes)

        </p>
     

        </div>
    
    <input type="submit" value="Create" class="btn btn-default" width="170" id="btnCreate" />


    @*<p>
            @(Html.Kendo().DropDownList()
            .Name("CmbLoggerType")

            .OptionLabel("Logger Type")
            .DataTextField("Text")
            .DataValueField("Value")
            .BindTo(new List<SelectListItem>() {
                new SelectListItem() {
                Text = "MultilogLX", Value = "1"
                },
                new SelectListItem() {
                Text = "FW-102-002U", Value = "2"
                },
                new SelectListItem() {
                Text = "Permalog", Value = "3"
                }
            })
                )
        </p>*@

            @*<p>
                @(Html.Kendo().DateTimePicker()
              .Name("DateStart")
              .Value(DateTime.Now)
              .HtmlAttributes(new { style = "width:175px" })
                )
            </p>

            <p>
                @(Html.Kendo().DateTimePicker()
              .Name("DateEnd")
              .Value(DateTime.Now)
              .HtmlAttributes(new { style = "width:175px" })
                )
            </p>

            <p>
                @(Html.Kendo().ComboBox()
          .Name("CmbNetwork")
          .Filter("contains")
          .Placeholder("Owner")
          .DataTextField("Text")
          .DataValueField("Value")
          .BindTo(new List<SelectListItem>() {
              new SelectListItem() {
                Text = "O2", Value = "1"
              },
              new SelectListItem() {
                Text = "Orange", Value = "2"
              },
              new SelectListItem() {
                Text = "T-Mobile", Value = "3"
              }
          })

          .Suggest(true)
                )
            </p>

            <p>
                @(Html.Kendo().AutoComplete()
        .Name("TxtLAC")
        .Placeholder("LAC")

                )
            </p>

            <p>
                @(Html.Kendo().AutoComplete()
        .Name("TxtCellID")
        .Placeholder("Cell ID")

                )
            </p>

            <p>
                @(Html.Kendo().AutoComplete()
        .Name("TxtMastLat")
        .Placeholder("Mast Lat")

                )
            </p>

            <p>
                @(Html.Kendo().AutoComplete()
        .Name("TxtMastLong")
        .Placeholder("Mast Long")
                )
            </p>

            <p>
                @(Html.Kendo().AutoComplete()
        .Name("TxtNotes")
        .Placeholder("Notes")
                )
            </p>*@
    
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">

    $(document).ready(function () {
        var site = $("#SitedID").data("kendoDropDownList");

        $("#WithSite").change(function () {
            var isChecked = $(this).is(':checked');
            site.enable(isChecked);
        });

    });

 </script>

HerculesSystem/Views/Logger/Edit.cshtml
@model HerculesSystem.Models.loggers

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
        <p>
            @Html.Hidden("InitialSMS", Model.LoggerSMSNumber)
            @Html.Label("SMS")
            @Html.TextBoxFor(model => model.LoggerSMSNumber, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.LoggerSMSNumber)
        </p>

        <p>
            @Html.Label("Serial Number")
            @Html.TextBoxFor(model => model.LoggerSerialNumber, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.LoggerSerialNumber)
        </p>

        <p>
            @(Html.CheckBox("WithSite")
            )
            @(Html.Label("Con Sites"))
        </p>

        <p>
            @(Html.Kendo().DropDownListFor(m => m.SiteID)
            .Name("SiteID")
            .Enable(false)
            .DataTextField("Adress")
            .DataValueField("ID")
            .DataSource(source =>
                {
                    source.Read(read =>
                    {
                        read.Action("GetSites", "Helper");
                    });
                })

            )
            <script>
                $('.SitedID').kendoDropDownList();
            </script>


        </p>

        <p>
            @Html.Label("Notes")
            @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", style = "width:175px" })
            @Html.ValidationMessageFor(model => model.Notes)

        </p>

        <p>
            @Html.Label("Adress")
            @Html.TextBoxFor(model => model.Adress, new { @class = "form-control", style = "width:175px" })
            @Html.ValidationMessageFor(model => model.Adress)
        </p>

        <p>
            @Html.Label("Logger Type")
            @(Html.Kendo().DropDownListFor(model => model.LoggerTypeClass)

          
            .DataTextField("Text")
            .DataValueField("Value")
            .BindTo(new List<SelectListItem>() {
                new SelectListItem() {
                Text = "ERP", Value = "ERP"
                },
                new SelectListItem() {
                Text = "PCP", Value = "PCP"
                }
            })
            )
            @Html.ValidationMessageFor(model => model.LoggerType)
        </p>

        <p>
            <style scoped>
                .k-button .k-image {
                    height: 20px;
                    width: 20px;
                }
            </style>

            @(Html.Kendo().Button()
                .Name("imageButton")
                .HtmlAttributes(new { type = "button" })
                .ImageUrl(Url.Content("~/Content/images/Location.png"))
                .Content("Map View")
                .SpriteCssClass("k.image")
            )
            @Html.Label("Lat East")
            @Html.TextBoxFor(model => model.LatEast, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.LatEast)
        </p>

        <p>
            @Html.Label("Long North")
            @Html.TextBoxFor(model => model.LongNorth, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.LongNorth)


        </p>

        <p>
            @Html.Label("Height AOD")
            @Html.TextBoxFor(model => model.HeightAOD, new { @class = "form-control", style = "width:170px" })
            @Html.ValidationMessageFor(model => model.HeightAOD)
        </p>

    </div>

    <input type="submit" value="Edit" class="btn btn-default" width="170" id="btnCreate" />

    <div id="map" style="width: 700px; height: 500px; " />

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" type="text/javascript"></script>
<script type="text/javascript">

    $(document).ready(function () {
        var site = $("#SiteID").data("kendoDropDownList");

        $("#WithSite").change(function () {
            var isChecked = $(this).is(':checked');
            site.enable(isChecked);
        });


        var ne = new google.maps.LatLng(-20.009901, -71.258046);
        var sw = new google.maps.LatLng(-20.009901, -71.258046);
        var bounds = new google.maps.LatLngBounds(ne, sw);

        var image2 = "@Url.Content("~/Content/images/Location.png")";

        $("#imageButton").kendoButton({
            imageUrl: image2
        });


        var options = {
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var googleMap = new google.maps.Map($("#map")[0], options);
        var infoWindow = new google.maps.InfoWindow({ content: "Cargando..." });


        $.ajax({

            success: function () {

                google.maps.event.addListener(googleMap, 'click', function (e) {

                    document.getElementById("LatEast").value = e.latLng.lat();
                    document.getElementById("LongNorth").value = e.latLng.lng();

                });
            }
        });

        googleMap.setCenter(bounds.getCenter());
        googleMap.setZoom(3);


    });

    var button = document.getElementById('imageButton');
    var div = document.getElementById('map');
    div.style.display = 'none'
    button.onclick = function () {
        var div = document.getElementById('map');
        if (div.style.display !== 'none') {
            div.style.display = 'none';

        }
        else {
            div.style.display = 'block';
            initialize();
        }
    };

    function initialize() {
        // create the map

        var myOptions = {
            zoom: 3,
            center: new google.maps.LatLng(0.0, 0.0),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var options = {
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        $.ajax({

            success: function () {

                google.maps.event.addListener(map, 'click', function (e) {

                    document.getElementById("LatEast").value = e.latLng.lat();
                    document.getElementById("LongNorth").value = e.latLng.lng();

                });
            }
        });

        map = new google.maps.Map(document.getElementById("map"),
                                    myOptions);

    }

</script>

HerculesSystem/Views/Logger/ListLogger.cshtml
@model IEnumerable<dynamic>

@{
    ViewBag.Title = "List Logger";
}

<link href="@Url.Content("~/Content/Logger/List.css")" rel="stylesheet" type="text/css" />
<h2>List Logger</h2>

<div class="demo-section k-header">
    <h4>Filter</h4>
    <p>
        @(Html.Kendo().DropDownList()
                    .Name("OwnerDropDownList") //The name of the dropdownlist is mandatory. It specifies the "id" attribute of the widget.
                    .DataTextField("UserName") //Specifies which property of the Product to be used by the dropdownlist as a text.
                    .DataValueField("ID") //Specifies which property of the Product to be used by the dropdownlist as a value.
                    .HtmlAttributes(new { style = "width:170px" })
                    .OptionLabel("Owner")
                    .DataSource(source =>
                    {
                        source.Read(read =>
                        {
                            read.Action("GetUser", "Helper"); //Set the Action and Controller name
                        }); //If true the DataSource will not filter the data on the client.
                    })
                    .Events(e =>
                    {
                        e.Change("onChangeOwner");
                    })
        )
    </p>

    <p>
        @(Html.Kendo().DropDownList()
                .Name("TypeDropDownList")
                .DataTextField("Text")
                .DataValueField("Value")
                .HtmlAttributes(new { style = "width:170px" })
                .OptionLabel("Logger Type")
                .BindTo(new List<SelectListItem>() {
                  new SelectListItem() {
                      Text = "FW-102-002U",
                      Value = "FW-102-002U"
                  },
                  new SelectListItem() {
                      Text = "Permalog",
                      Value = "Permalog"
                  },
                  new SelectListItem() {
                      Text = "DW-102-0023",
                      Value = "DW-102-0023"
                  }
              })
                       .Events(e =>
                            {
                                e.Change("onChangeType");
                            })
        )
</p>

    @(Html.Kendo().Button()
        .Name("linkButton")
        .Tag("a")
        
        .Content("Create")
        .Events(e =>
        {
            e.Click("ClickCreate");
        })
    )

</div>



<div id="grid" class="grid">  

    @(Html.Kendo().Grid(Model).Name("GridLoggers")
      .DataSource(ds => ds.Ajax()
            .Model(c =>
            {
                c.Id("ID");
                c.Field("LoggerSMSNumber",typeof(int));
                c.Field("BatteryLevel", typeof(int));
                c.Field("CreationDate", typeof(DateTime));
                c.Field("LoggerSerialNumber", typeof(int));
                c.Field("LoggerType", typeof(string));
                c.Field("SignalLevel", typeof(int));
                c.Field("Adress", typeof(string));
                c.Field("Owner", typeof(string));
                c.Field("OwnerID", typeof(int));
              
            })
            .Read(r => r.Action("Read", "Logger"))
            .Create(u => u.Action("Create", "Home"))
            .Destroy(u => u.Action("Delete", "Logger"))
           
            )
            
            .Columns(columns =>
                {
                    columns.Bound("LoggerSMSNumber").Title("SMS");
                    columns.Bound("Adress").Title("Adress");
                    columns.Bound("LoggerSerialNumber").Title("Serial Number");
                    columns.Bound("Owner").Title("Owner");
                   // columns.Bound("BatteryLevel").Title("Battery Level");
                    columns.Bound("CreationDate").Title("Creation Date").Format("{0:dd/MM/yyyy HH:mm:ss}");
                    columns.Bound("LoggerType").Title("Type");
                    //columns.Bound("SignalLevel").Title("Signal Level");
                   
                    
                    columns.Command(command =>
                    {
                        command.Custom("View").Click("ViewDetail");
                        command.Destroy().Text("Delete");
                        command.Custom("Edit").Click("EditDetail");
                    });
                    
                })
                       .Editable(editable => editable.TemplateName("ProductItem").Mode(GridEditMode.PopUp))
                        
                        .Sortable()
                        .Filterable()
                        .Pageable()
                        
      )
           

</div>

<script type="text/javascript">

    var detailsTemplate = kendo.template($("#template").html());

    function ViewDetail(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var stockReceiptId = dataItem.ID;
        window.location.href = "@Url.Action("DetailButton", "Logger")?ID=" + stockReceiptId;

    }

    function EditDetail(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var stockReceiptId = dataItem.ID;
        window.location.href = "@Url.Action("Edit", "Logger")?ID=" + stockReceiptId;

    }

    function FilterGrid() {
        var Owner = $("#OwnerDropDownList").val(),
        Type = $("#TypeDropDownList").val();

        window.location.href = "@Url.Action("FilterButton", "Logger")?OwnerID=" + Owner + "?LoggerType=" + Type;
    }


    function filterLogger() {
        return {
            OwnerDropDownList: $("#OwnerDropDownList").val()
        };
    }

    $(document).ready(function () {
        var owner = $("#OwnerDropDownList").data("kendoDropDownList");
    });

    function onChangeOwner() {
        applyFilter("OwnerID", $("#OwnerDropDownList").val());
    }

    function onChangeType() {
        applyFilter("LoggerType", $("#TypeDropDownList").val());
    }


    function applyFilter(filterField, filterValue) {

        // get the kendoGrid element.
        var gridData = $("#GridLoggers").data("kendoGrid");

        // get currently applied filters from the Grid.
        var currFilterObj = gridData.dataSource.filter();

        var currentFilters = currFilterObj ? currFilterObj.filters : [];


        if (currentFilters && currentFilters.length > 0) {
            for (var i = 0; i < currentFilters.length; i++) {
                if (currentFilters[i].field == filterField) {
                    currentFilters.splice(i, 1);
                    break;
                }
            }
        }

        if (filterValue != "") {
            currentFilters.push({
                field: filterField,
                operator: "eq",
                value: filterValue
            });
        }

        // finally, the currentFilters array is applied back to the Grid, using "and" logic.
        gridData.dataSource.filter({
            logic: "and",
            filters: currentFilters
        });

    }

    function ClickCreate(e) {

        window.location.href = "@Url.Action("Create", "Logger")";
    }


</script>

HerculesSystem/Views/Logger/Loading.cshtml
@{
    ViewBag.Title = "Loading";
}

<h2>Loading</h2>